var arrQarat = [
    {},
    {
        name: 'آسيا',
        id: 'qarat_02',
        bg: 'maps/qarat/2/bg.png',
        scale: 500,
        items: [{
            text: "اليابان",
            id: "btn01",
            layer: "maps/qarat/2/01.png",
            icon: "maps/qarat/2/01c.png"
        }, {
            text: "الهند",
            id: "btn02",
            layer: "maps/qarat/2/02.png",
            icon: "maps/qarat/2/02c.png"
        }, {
            text: "الكويت",
            id: "btn03",
            layer: "maps/qarat/2/03.png",
            icon: "maps/qarat/2/03c.png"
        }, {
            text: "الفلبين",
            id: "btn04",
            layer: "maps/qarat/2/04.png",
            icon: "maps/qarat/2/04c.png"
        }, {
            text: "العراق",
            id: "btn05",
            layer: "maps/qarat/2/05.png",
            icon: "maps/qarat/2/05c.png"
        }, {
            text: "الصين",
            id: "btn06",
            layer: "maps/qarat/2/06.png",
            icon: "maps/qarat/2/06c.png"
        }, {
            text: "السعودية",
            id: "btn07",
            layer: "maps/qarat/2/07.png",
            icon: "maps/qarat/2/07c.png"
        }, {
            text: "البحرين",
            id: "btn08",
            layer: "maps/qarat/2/08.png",
            icon: "maps/qarat/2/08c.png"
        }, {
            text: "الإمارات",
            id: "btn09",
            layer: "maps/qarat/2/09.png",
            icon: "maps/qarat/2/09c.png"
        }, {
            text: "الأردن",
            id: "btn10",
            layer: "maps/qarat/2/10.png",
            icon: "maps/qarat/2/10c.png"
        }, {
            text: "أفغانستان",
            id: "btn11",
            layer: "maps/qarat/2/11.png",
            icon: "maps/qarat/2/11c.png"
        }, {
            text: "أرمينيا",
            id: "btn12",
            layer: "maps/qarat/2/12.png",
            icon: "maps/qarat/2/12c.png"
        }, {
            text: "أذربيجان",
            id: "btn13",
            layer: "maps/qarat/2/13.png",
            icon: "maps/qarat/2/13c.png"
        }, {
            text: "تيمور الشرقية",
            id: "btn14",
            layer: "maps/qarat/2/14.png",
            icon: "maps/qarat/2/14c.png"
        }, {
            text: "تركيا",
            id: "btn15",
            layer: "maps/qarat/2/15.png",
            icon: "maps/qarat/2/15c.png"
        }, {
            text: "تركمانستان",
            id: "btn16",
            layer: "maps/qarat/2/16.png",
            icon: "maps/qarat/2/16c.png"
        }, {
            text: "تايوان",
            id: "btn17",
            layer: "maps/qarat/2/17.png",
            icon: "maps/qarat/2/17c.png"
        }, {
            text: "تايلاند",
            id: "btn18",
            layer: "maps/qarat/2/18.png",
            icon: "maps/qarat/2/18c.png"
        }, {
            text: "بوتان",
            id: "btn19",
            layer: "maps/qarat/2/19.png",
            icon: "maps/qarat/2/19c.png"
        }, {
            text: "بنجلادش",
            id: "btn20",
            layer: "maps/qarat/2/20.png",
            icon: "maps/qarat/2/20c.png"
        }, {
            text: "بروناي",
            id: "btn21",
            layer: "maps/qarat/2/21.png",
            icon: "maps/qarat/2/21c.png"
        }, {
            text: "باكستان",
            id: "btn22",
            layer: "maps/qarat/2/22.png",
            icon: "maps/qarat/2/22c.png"
        }, {
            text: "إيران",
            id: "btn23",
            layer: "maps/qarat/2/23.png",
            icon: "maps/qarat/2/23c.png"
        }, {
            text: "أوزباكستان",
            id: "btn24",
            layer: "maps/qarat/2/24.png",
            icon: "maps/qarat/2/24c.png"
        }, {
            text: "إندونيسيا",
            id: "btn25",
            layer: "maps/qarat/2/25.png",
            icon: "maps/qarat/2/25c.png"
        }, {
            text: "اليمن",
            id: "btn26",
            layer: "maps/qarat/2/26.png",
            icon: "maps/qarat/2/26c.png"
        }, {
            text: "كوريا الجنوبية",
            id: "btn27",
            layer: "maps/qarat/2/27.png",
            icon: "maps/qarat/2/27c.png"
        }, {
            text: "كامبوديا",
            id: "btn28",
            layer: "maps/qarat/2/28.png",
            icon: "maps/qarat/2/28c.png"
        }, {
            text: "كازاخستان",
            id: "btn29",
            layer: "maps/qarat/2/29.png",
            icon: "maps/qarat/2/29c.png"
        }, {
            text: "قرغيزيا",
            id: "btn30",
            layer: "maps/qarat/2/30.png",
            icon: "maps/qarat/2/30c.png"
        }, {
            text: "فيتنام",
            id: "btn31",
            layer: "maps/qarat/2/31.png",
            icon: "maps/qarat/2/31c.png"
        }, {
            text: "فلسطين",
            id: "btn32",
            layer: "maps/qarat/2/32.png",
            icon: "maps/qarat/2/32c.png"
        }, {
            text: "عمان",
            id: "btn33",
            layer: "maps/qarat/2/33.png",
            icon: "maps/qarat/2/33c.png"
        }, {
            text: "طاجيستان",
            id: "btn34",
            layer: "maps/qarat/2/34.png",
            icon: "maps/qarat/2/34c.png"
        }, {
            text: "سوريا",
            id: "btn35",
            layer: "maps/qarat/2/35.png",
            icon: "maps/qarat/2/35c.png"
        }, {
            text: "سنغافورة",
            id: "btn36",
            layer: "maps/qarat/2/36.png",
            icon: "maps/qarat/2/36c.png"
        }, {
            text: "سريلانكا",
            id: "btn37",
            layer: "maps/qarat/2/37.png",
            icon: "maps/qarat/2/37c.png"
        }, {
            text: "روسيا",
            id: "btn38",
            layer: "maps/qarat/2/38.png",
            icon: "maps/qarat/2/38c.png"
        }, {
            text: "جورجيا",
            id: "btn39",
            layer: "maps/qarat/2/39.png",
            icon: "maps/qarat/2/39c.png"
        }, {
            text: "نيبال",
            id: "btn40",
            layer: "maps/qarat/2/40.png",
            icon: "maps/qarat/2/40c.png"
        }, {
            text: "ميانهار",
            id: "btn41",
            layer: "maps/qarat/2/41.png",
            icon: "maps/qarat/2/41c.png"
        }, {
            text: "منغوليا",
            id: "btn42",
            layer: "maps/qarat/2/42.png",
            icon: "maps/qarat/2/42c.png"
        }, {
            text: "ماليزيا",
            id: "btn43",
            layer: "maps/qarat/2/43.png",
            icon: "maps/qarat/2/43c.png"
        }, {
            text: "لبنان",
            id: "btn44",
            layer: "maps/qarat/2/44.png",
            icon: "maps/qarat/2/44c.png"
        }, {
            text: "لاوس",
            id: "btn45",
            layer: "maps/qarat/2/45.png",
            icon: "maps/qarat/2/45c.png"
        }, {
            text: "كوريا الشمالية",
            id: "btn46",
            layer: "maps/qarat/2/46.png",
            icon: "maps/qarat/2/46c.png"
        }, ]

    },
    {},
    {
        name: 'أفريقيا',
        id: 'qarat_04',
        bg: 'maps/qarat/4/bg.png',
        scale: 500,
        items: [{
            text: "أنجولا",
            id: "btn01",
            layer: "maps/qarat/4/01.png",
            icon: "maps/qarat/4/01c.png"
        }, {
            text: "أوغندا",
            id: "btn02",
            layer: "maps/qarat/4/02.png",
            icon: "maps/qarat/4/02c.png"
        }, {
            text: "إثيوبيا",
            id: "btn03",
            layer: "maps/qarat/4/03.png",
            icon: "maps/qarat/4/03c.png"
        }, {
            text: "إريتريا",
            id: "btn04",
            layer: "maps/qarat/4/04.png",
            icon: "maps/qarat/4/04c.png"
        }, {
            text: "إفريقيا الوسطى",
            id: "btn05",
            layer: "maps/qarat/4/05.png",
            icon: "maps/qarat/4/05c.png"
        }, {
            text: "الجابون",
            id: "btn06",
            layer: "maps/qarat/4/06.png",
            icon: "maps/qarat/4/06c.png"
        }, {
            text: "الجزائر",
            id: "btn07",
            layer: "maps/qarat/4/07.png",
            icon: "maps/qarat/4/07c.png"
        }, {
            text: "الجماهيرية العربية الليبية",
            id: "btn08",
            layer: "maps/qarat/4/08.png",
            icon: "maps/qarat/4/08c.png"
        }, {
            text: "الرأس الأخضر",
            id: "btn09",
            layer: "maps/qarat/4/09.png",
            icon: "maps/qarat/4/09c.png"
        }, {
            text: "السنغال",
            id: "btn10",
            layer: "maps/qarat/4/10.png",
            icon: "maps/qarat/4/10c.png"
        }, {
            text: "السودان",
            id: "btn11",
            layer: "maps/qarat/4/11.png",
            icon: "maps/qarat/4/11c.png"
        }, {
            text: "الصحراء الغربية",
            id: "btn12",
            layer: "maps/qarat/4/12.png",
            icon: "maps/qarat/4/12c.png"
        }, {
            text: "الصومال",
            id: "btn13",
            layer: "maps/qarat/4/13.png",
            icon: "maps/qarat/4/13c.png"
        }, {
            text: "الكاميرون",
            id: "btn14",
            layer: "maps/qarat/4/14.png",
            icon: "maps/qarat/4/14c.png"
        }, {
            text: "الكونغو",
            id: "btn15",
            layer: "maps/qarat/4/15.png",
            icon: "maps/qarat/4/15c.png"
        }, {
            text: "المغرب",
            id: "btn16",
            layer: "maps/qarat/4/16.png",
            icon: "maps/qarat/4/16c.png"
        }, {
            text: "النيجر ",
            id: "btn17",
            layer: "maps/qarat/4/17.png",
            icon: "maps/qarat/4/17c.png"
        }, {
            text: "بنين",
            id: "btn18",
            layer: "maps/qarat/4/18.png",
            icon: "maps/qarat/4/18c.png"
        }, {
            text: "بوتسوانا",
            id: "btn19",
            layer: "maps/qarat/4/19.png",
            icon: "maps/qarat/4/19c.png"
        }, {
            text: "بوركينا فاسو",
            id: "btn20",
            layer: "maps/qarat/4/20.png",
            icon: "maps/qarat/4/20c.png"
        }, {
            text: "بوروندي",
            id: "btn21",
            layer: "maps/qarat/4/21.png",
            icon: "maps/qarat/4/21c.png"
        }, {
            text: "تشاد",
            id: "btn22",
            layer: "maps/qarat/4/22.png",
            icon: "maps/qarat/4/22c.png"
        }, {
            text: "تنزانيا",
            id: "btn23",
            layer: "maps/qarat/4/23.png",
            icon: "maps/qarat/4/23c.png"
        }, {
            text: "توجو",
            id: "btn24",
            layer: "maps/qarat/4/24.png",
            icon: "maps/qarat/4/24c.png"
        }, {
            text: "تونس",
            id: "btn25",
            layer: "maps/qarat/4/25.png",
            icon: "maps/qarat/4/25c.png"
        }, {
            text: "جامبيا",
            id: "btn26",
            layer: "maps/qarat/4/26.png",
            icon: "maps/qarat/4/26c.png"
        }, {
            text: "جزر القمر",
            id: "btn27",
            layer: "maps/qarat/4/27.png",
            icon: "maps/qarat/4/27c.png"
        }, {
            text: "جمهورية الكوغو الديموقراطية",
            id: "btn28",
            layer: "maps/qarat/4/28.png",
            icon: "maps/qarat/4/28c.png"
        }, {
            text: "جنوب إفريقيا",
            id: "btn29",
            layer: "maps/qarat/4/29.png",
            icon: "maps/qarat/4/29c.png"
        }, {
            text: "جنوب السودان",
            id: "btn30",
            layer: "maps/qarat/4/30.png",
            icon: "maps/qarat/4/30c.png"
        }, {
            text: "جيبوتي",
            id: "btn31",
            layer: "maps/qarat/4/31.png",
            icon: "maps/qarat/4/31c.png"
        }, {
            text: "رواندا",
            id: "btn32",
            layer: "maps/qarat/4/32.png",
            icon: "maps/qarat/4/32c.png"
        }, {
            text: "زامبيا",
            id: "btn33",
            layer: "maps/qarat/4/33.png",
            icon: "maps/qarat/4/33c.png"
        }, {
            text: "زيمبابوي",
            id: "btn34",
            layer: "maps/qarat/4/34.png",
            icon: "maps/qarat/4/34c.png"
        }, {
            text: "ساحل العاج",
            id: "btn35",
            layer: "maps/qarat/4/35.png",
            icon: "maps/qarat/4/35c.png"
        }, {
            text: "ساوتومي وبرينسيب",
            id: "btn36",
            layer: "maps/qarat/4/36.png",
            icon: "maps/qarat/4/36c.png"
        }, {
            text: "سوازيلاند",
            id: "btn37",
            layer: "maps/qarat/4/37.png",
            icon: "maps/qarat/4/37c.png"
        }, {
            text: "سيراليون",
            id: "btn38",
            layer: "maps/qarat/4/38.png",
            icon: "maps/qarat/4/38c.png"
        }, {
            text: "سيشيل",
            id: "btn39",
            layer: "maps/qarat/4/39.png",
            icon: "maps/qarat/4/39c.png"
        }, {
            text: "غانا",
            id: "btn40",
            layer: "maps/qarat/4/40.png",
            icon: "maps/qarat/4/40c.png"
        }, {
            text: "غينيا",
            id: "btn41",
            layer: "maps/qarat/4/41.png",
            icon: "maps/qarat/4/41c.png"
        }, {
            text: "غينيا الاستوائية",
            id: "btn42",
            layer: "maps/qarat/4/42.png",
            icon: "maps/qarat/4/42c.png"
        }, {
            text: "غينيا بسياو",
            id: "btn43",
            layer: "maps/qarat/4/43.png",
            icon: "maps/qarat/4/43c.png"
        }, {
            text: "كينيا",
            id: "btn44",
            layer: "maps/qarat/4/44.png",
            icon: "maps/qarat/4/44c.png"
        }, {
            text: "ليبيريا",
            id: "btn45",
            layer: "maps/qarat/4/45.png",
            icon: "maps/qarat/4/45c.png"
        }, {
            text: "ليسوثو",
            id: "btn46",
            layer: "maps/qarat/4/46.png",
            icon: "maps/qarat/4/46c.png"
        }, {
            text: "مالاوي",
            id: "btn47",
            layer: "maps/qarat/4/47.png",
            icon: "maps/qarat/4/47c.png"
        }, {
            text: "مالي",
            id: "btn48",
            layer: "maps/qarat/4/48.png",
            icon: "maps/qarat/4/48c.png"
        }, {
            text: "مدغشقر",
            id: "btn49",
            layer: "maps/qarat/4/49.png",
            icon: "maps/qarat/4/49c.png"
        }, {
            text: "مصر",
            id: "btn50",
            layer: "maps/qarat/4/50.png",
            icon: "maps/qarat/4/50c.png"
        }, {
            text: "موريتانيا",
            id: "btn51",
            layer: "maps/qarat/4/51.png",
            icon: "maps/qarat/4/51c.png"
        }, {
            text: "موريشيوس",
            id: "btn52",
            layer: "maps/qarat/4/52.png",
            icon: "maps/qarat/4/52c.png"
        }, {
            text: "موزمبيق",
            id: "btn53",
            layer: "maps/qarat/4/53.png",
            icon: "maps/qarat/4/53c.png"
        }, {
            text: "نامبيا",
            id: "btn54",
            layer: "maps/qarat/4/54.png",
            icon: "maps/qarat/4/54c.png"
        }, ]
    },
    {},
    {
        name: 'أوروبا',
        id: 'qarat_06',
        bg: 'maps/qarat/6/bg.png',
        scale: 200,
        items: [{
            text: "آيسلندا",
            id: "btn01",
            layer: "maps/qarat/6/01.png",
            icon: "maps/qarat/6/01c.png"
        }, {
            text: "أكرانيا",
            id: "btn02",
            layer: "maps/qarat/6/02.png",
            icon: "maps/qarat/6/02c.png"
        }, {
            text: "ألبانيا",
            id: "btn03",
            layer: "maps/qarat/6/03.png",
            icon: "maps/qarat/6/03c.png"
        }, {
            text: "ألمانيا",
            id: "btn04",
            layer: "maps/qarat/6/04.png",
            icon: "maps/qarat/6/04c.png"
        }, {
            text: "أندورا",
            id: "btn05",
            layer: "maps/qarat/6/05.png",
            icon: "maps/qarat/6/05c.png"
        }, {
            text: "أيرالندا",
            id: "btn06",
            layer: "maps/qarat/6/06.png",
            icon: "maps/qarat/6/06c.png"
        }, {
            text: "إسبانيا",
            id: "btn07",
            layer: "maps/qarat/6/07.png",
            icon: "maps/qarat/6/07c.png"
        }, {
            text: "إستونيا",
            id: "btn08",
            layer: "maps/qarat/6/08.png",
            icon: "maps/qarat/6/08c.png"
        }, {
            text: "إيطاليا",
            id: "btn09",
            layer: "maps/qarat/6/09.png",
            icon: "maps/qarat/6/09c.png"
        }, {
            text: "البرتغال",
            id: "btn10",
            layer: "maps/qarat/6/10.png",
            icon: "maps/qarat/6/10c.png"
        }, {
            text: "البوسنة والهرسك",
            id: "btn11",
            layer: "maps/qarat/6/11.png",
            icon: "maps/qarat/6/11c.png"
        }, {
            text: "الجبل الأسود",
            id: "btn12",
            layer: "maps/qarat/6/12.png",
            icon: "maps/qarat/6/12c.png"
        }, {
            text: "الدنمارك",
            id: "btn13",
            layer: "maps/qarat/6/13.png",
            icon: "maps/qarat/6/13c.png"
        }, {
            text: "السويد",
            id: "btn14",
            layer: "maps/qarat/6/14.png",
            icon: "maps/qarat/6/14c.png"
        }, {
            text: "هنجاريا",
            id: "btn15",
            layer: "maps/qarat/6/15.png",
            icon: "maps/qarat/6/15c.png"
        }, {
            text: "المملكة المتحدة",
            id: "btn16",
            layer: "maps/qarat/6/16.png",
            icon: "maps/qarat/6/16c.png"
        }, {
            text: "النرويج",
            id: "btn17",
            layer: "maps/qarat/6/17.png",
            icon: "maps/qarat/6/17c.png"
        }, {
            text: "النمسا",
            id: "btn18",
            layer: "maps/qarat/6/18.png",
            icon: "maps/qarat/6/18c.png"
        }, {
            text: "اليونان",
            id: "btn19",
            layer: "maps/qarat/6/19.png",
            icon: "maps/qarat/6/19c.png"
        }, {
            text: "بلجيكا",
            id: "btn20",
            layer: "maps/qarat/6/20.png",
            icon: "maps/qarat/6/20c.png"
        }, {
            text: "بلغاريا",
            id: "btn21",
            layer: "maps/qarat/6/21.png",
            icon: "maps/qarat/6/21c.png"
        }, {
            text: "بولندا",
            id: "btn22",
            layer: "maps/qarat/6/22.png",
            icon: "maps/qarat/6/22c.png"
        }, {
            text: "تركيا",
            id: "btn23",
            layer: "maps/qarat/6/23.png",
            icon: "maps/qarat/6/23c.png"
        }, {
            text: "جمهورية التشيك",
            id: "btn24",
            layer: "maps/qarat/6/24.png",
            icon: "maps/qarat/6/24c.png"
        }, {
            text: "جمهورية مولدوفا",
            id: "btn25",
            layer: "maps/qarat/6/25.png",
            icon: "maps/qarat/6/25c.png"
        }, {
            text: "روسيا",
            id: "btn26",
            layer: "maps/qarat/6/26.png",
            icon: "maps/qarat/6/26c.png"
        }, {
            text: "روسيا البيضاء",
            id: "btn27",
            layer: "maps/qarat/6/27.png",
            icon: "maps/qarat/6/27c.png"
        }, {
            text: "رومانيا",
            id: "btn28",
            layer: "maps/qarat/6/28.png",
            icon: "maps/qarat/6/28c.png"
        }, {
            text: "سان مارينو",
            id: "btn29",
            layer: "maps/qarat/6/29.png",
            icon: "maps/qarat/6/29c.png"
        }, {
            text: "سلوفاكيا",
            id: "btn30",
            layer: "maps/qarat/6/30.png",
            icon: "maps/qarat/6/30c.png"
        }, {
            text: "سلوفينيا",
            id: "btn31",
            layer: "maps/qarat/6/31.png",
            icon: "maps/qarat/6/31c.png"
        }, {
            text: "سويسرا",
            id: "btn32",
            layer: "maps/qarat/6/32.png",
            icon: "maps/qarat/6/32c.png"
        }, {
            text: "صربيا",
            id: "btn33",
            layer: "maps/qarat/6/33.png",
            icon: "maps/qarat/6/33c.png"
        }, {
            text: "فرنسا",
            id: "btn34",
            layer: "maps/qarat/6/34.png",
            icon: "maps/qarat/6/34c.png"
        }, {
            text: "فنلندا",
            id: "btn35",
            layer: "maps/qarat/6/35.png",
            icon: "maps/qarat/6/35c.png"
        }, {
            text: "قبرص",
            id: "btn36",
            layer: "maps/qarat/6/36.png",
            icon: "maps/qarat/6/36c.png"
        }, {
            text: "كرواتيا",
            id: "btn37",
            layer: "maps/qarat/6/37.png",
            icon: "maps/qarat/6/37c.png"
        }, {
            text: "لاتفيا",
            id: "btn38",
            layer: "maps/qarat/6/38.png",
            icon: "maps/qarat/6/38c.png"
        }, {
            text: "لوكسمبرج",
            id: "btn39",
            layer: "maps/qarat/6/39.png",
            icon: "maps/qarat/6/39c.png"
        }, {
            text: "ليتوانيا",
            id: "btn40",
            layer: "maps/qarat/6/40.png",
            icon: "maps/qarat/6/40c.png"
        }, {
            text: "ليختنشتاين",
            id: "btn41",
            layer: "maps/qarat/6/41.png",
            icon: "maps/qarat/6/41c.png"
        }, {
            text: "مالطا",
            id: "btn42",
            layer: "maps/qarat/6/42.png",
            icon: "maps/qarat/6/42c.png"
        }, {
            text: "مقدونيا",
            id: "btn43",
            layer: "maps/qarat/6/43.png",
            icon: "maps/qarat/6/43c.png"
        }, {
            text: "موناكو",
            id: "btn44",
            layer: "maps/qarat/6/44.png",
            icon: "maps/qarat/6/44c.png"
        }, {
            text: "هولندا",
            id: "btn45",
            layer: "maps/qarat/6/45.png",
            icon: "maps/qarat/6/45c.png"
        }, ]

    },
    {},
    {

        name: 'أمريكا الشمالية',
        id: 'qarat_08',
        bg: 'maps/qarat/8/bg.png',
        scale: 500,
        items: [{
            text: "أنتيغوا وباربودا",
            id: "btn01",
            layer: "maps/qarat/8/01.png",
            icon: "maps/qarat/8/01c.png"
        }, {
            text: "أنجويلا",
            id: "btn02",
            layer: "maps/qarat/8/02.png",
            icon: "maps/qarat/8/02c.png"
        }, {
            text: "السلفادور",
            id: "btn03",
            layer: "maps/qarat/8/03.png",
            icon: "maps/qarat/8/03c.png"
        }, {
            text: "المكسيك",
            id: "btn04",
            layer: "maps/qarat/8/04.png",
            icon: "maps/qarat/8/04c.png"
        }, {
            text: "الولايات المتحدة الأمريكية",
            id: "btn05",
            layer: "maps/qarat/8/05.png",
            icon: "maps/qarat/8/05c.png"
        }, {
            text: "باربادوس",
            id: "btn06",
            layer: "maps/qarat/8/06.png",
            icon: "maps/qarat/8/06c.png"
        }, {
            text: "برمودا",
            id: "btn07",
            layer: "maps/qarat/8/07.png",
            icon: "maps/qarat/8/07c.png"
        }, {
            text: "بليز",
            id: "btn08",
            layer: "maps/qarat/8/08.png",
            icon: "maps/qarat/8/08c.png"
        }, {
            text: "بنما",
            id: "btn09",
            layer: "maps/qarat/8/09.png",
            icon: "maps/qarat/8/09c.png"
        }, {
            text: "بورتوريكو",
            id: "btn10",
            layer: "maps/qarat/8/10.png",
            icon: "maps/qarat/8/10c.png"
        }, {
            text: "ترينداد وتوباجو",
            id: "btn11",
            layer: "maps/qarat/8/11.png",
            icon: "maps/qarat/8/11c.png"
        }, {
            text: "جامايكا",
            id: "btn12",
            layer: "maps/qarat/8/12.png",
            icon: "maps/qarat/8/12c.png"
        }, {
            text: "جرين لاند",
            id: "btn13",
            layer: "maps/qarat/8/13.png",
            icon: "maps/qarat/8/13c.png"
        }, {
            text: "جرينادا",
            id: "btn14",
            layer: "maps/qarat/8/14.png",
            icon: "maps/qarat/8/14c.png"
        }, {
            text: "جزر الباهاما",
            id: "btn15",
            layer: "maps/qarat/8/15.png",
            icon: "maps/qarat/8/15c.png"
        }, {
            text: "جمهورية الدومينيكان",
            id: "btn16",
            layer: "maps/qarat/8/16.png",
            icon: "maps/qarat/8/16c.png"
        }, {
            text: "جواتيمالا",
            id: "btn17",
            layer: "maps/qarat/8/17.png",
            icon: "maps/qarat/8/17c.png"
        }, {
            text: "جوادلوب",
            id: "btn18",
            layer: "maps/qarat/8/18.png",
            icon: "maps/qarat/8/18c.png"
        }, {
            text: "دومينيكا",
            id: "btn19",
            layer: "maps/qarat/8/19.png",
            icon: "maps/qarat/8/19c.png"
        }, {
            text: "سانت فنسنت والجرينادين",
            id: "btn20",
            layer: "maps/qarat/8/20.png",
            icon: "maps/qarat/8/20c.png"
        }, {
            text: "سانت كيتس ونيغيس",
            id: "btn21",
            layer: "maps/qarat/8/21.png",
            icon: "maps/qarat/8/21c.png"
        }, {
            text: "كندا و كوبا",
            id: "btn22",
            layer: "maps/qarat/8/22.png",
            icon: "maps/qarat/8/22c.png"
        }, {
            text: "كوستاريكا",
            id: "btn23",
            layer: "maps/qarat/8/23.png",
            icon: "maps/qarat/8/23c.png"
        }, {
            text: "مونتسرات",
            id: "btn24",
            layer: "maps/qarat/8/24.png",
            icon: "maps/qarat/8/24c.png"
        }, {
            text: "نيكاراجوا",
            id: "btn25",
            layer: "maps/qarat/8/25.png",
            icon: "maps/qarat/8/25c.png"
        }, {
            text: "هايتي",
            id: "btn26",
            layer: "maps/qarat/8/26.png",
            icon: "maps/qarat/8/26c.png"
        }, {
            text: "هندوراس",
            id: "btn27",
            layer: "maps/qarat/8/27.png",
            icon: "maps/qarat/8/27c.png"
        }, ]


    },
    {},
    {

        name: 'أمريكا الجنوبية',
        id: 'qarat_10',
        bg: 'maps/qarat/10/bg.png',
        scale: 500,
        items: [{
            text: "الأرجنتين",
            id: "btn01",
            layer: "maps/qarat/10/01.png",
            icon: "maps/qarat/10/01c.png"
        }, {
            text: "الإكوادور",
            id: "btn02",
            layer: "maps/qarat/10/02.png",
            icon: "maps/qarat/10/02c.png"
        }, {
            text: "الأوروجواي",
            id: "btn03",
            layer: "maps/qarat/10/03.png",
            icon: "maps/qarat/10/03c.png"
        }, {
            text: "الباراجواي",
            id: "btn04",
            layer: "maps/qarat/10/04.png",
            icon: "maps/qarat/10/04c.png"
        }, {
            text: "البرازيل",
            id: "btn05",
            layer: "maps/qarat/10/05.png",
            icon: "maps/qarat/10/05c.png"
        }, {
            text: "بوليفيا",
            id: "btn06",
            layer: "maps/qarat/10/06.png",
            icon: "maps/qarat/10/06c.png"
        }, {
            text: "بيرو",
            id: "btn07",
            layer: "maps/qarat/10/07.png",
            icon: "maps/qarat/10/07c.png"
        }, {
            text: "جزر فوكلاند",
            id: "btn08",
            layer: "maps/qarat/10/08.png",
            icon: "maps/qarat/10/08c.png"
        }, {
            text: "سورينام",
            id: "btn09",
            layer: "maps/qarat/10/09.png",
            icon: "maps/qarat/10/09c.png"
        }, {
            text: "شيلي",
            id: "btn10",
            layer: "maps/qarat/10/10.png",
            icon: "maps/qarat/10/10c.png"
        }, {
            text: "غويانا",
            id: "btn11",
            layer: "maps/qarat/10/11.png",
            icon: "maps/qarat/10/11c.png"
        }, {
            text: "جيانا الفرنسية",
            id: "btn12",
            layer: "maps/qarat/10/12.png",
            icon: "maps/qarat/10/12c.png"
        }, {
            text: "فينزويلا",
            id: "btn13",
            layer: "maps/qarat/10/13.png",
            icon: "maps/qarat/10/13c.png"
        }, {
            text: "كولومبيا",
            id: "btn14",
            layer: "maps/qarat/10/14.png",
            icon: "maps/qarat/10/14c.png"
        }, ]

    },
    {},

];